from app import db
from hashlib import md5
import app.queries.evernquery as evernquery
from bs4 import BeautifulSoup

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    nickname = db.Column(db.String(64), index=True, unique=True)
    email = db.Column(db.String(120), index=True, unique=True)
    posts = db.relationship('Post', backref='author', lazy='dynamic')
    about_me = db.Column(db.String(140))
    last_seen = db.Column(db.DateTime)

    def is_authenticated(self):
        """returns false if user is not allowed to authenticate"""
        return True # pass for now

    def is_active(self):
        """returns false if user has been banned (for example)"""
        return True

    def is_anonymous(self):
        return False

    def get_id(self):
        """returns unique id generated by db layer for user"""
        return unicode(self.id) # python 2

    def avatar(self, size):
        """grabs the user's gravatar"""
        return 'http://www.gravatar.com/avatar/%s?d=mm&s=%d' % (md5(self.email.encode('utf-8')).hexdigest(), size)

    def get_todo_content(self):
        """call queries/evernquery.get_todo_notes. return a list of all divs
        that contain en-todo tags along with their 'checked' status. seperate
        text not associated with en-todo tags and pass that along as well."""
        soup = BeautifulSoup(evernquery.get_todo_notes().content)
        all_divs = soup.findAll("div")
        out_divs = []
        for div in all_divs:
            if div.contents[0].name == "en-todo":
                div['id'] = 'tdcontent'
                try:
                    if div.contents[0]['checked'] == 'true':
                        div.contents[0]['checked'] = 'checked' # change "checked" attr to jquery-compatible
                except KeyError: # en-todo is not checked. pass on to jquery as is
                    pass
                out_divs.append([div, 'checked' in div.contents[0].attrs])
            else:
                div['id'] = 'tdheader'
                out_divs.append([div, "something's wrong if this gets touched"])
        return out_divs

    def __repr__(self):
        """how to print items from the db. used for debugging"""
        return "<User %r>" % (self.nickname)

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    body = db.Column(db.String(140))
    timestamp = db.Column(db.DateTime)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    def __repr__(self):
        return '<Post %r>' % (self.body)
